Image uploading component and user from session hook
MarketMate-Seng480/MarketMate pull request #107
Opened 2024-03-17 01:46 UTC by JonCote

Component ImageUpload.tsx for uploading images to the Supabase storage, built using uppy to enable uploading of files.
Added useUser() hook to get user data from current session. 
useUser() makes use of tanstack for query provider.
Added QueryProvider to layout.tsx to support the useUser(), not sure if query-provider.tsx in components should be moved to the provider script or if current implementation is fine.

the useUser() hook enables current user data to be pull as such: const {data:user} = useUser(), and is imported from /lib/hooks

2024-03-17 06:32 UTC, maddiesolis requested changes

2024-03-17 06:32 UTC, maddiesolis commented on marketmate/src/app/_components/ImageUpload.tsx
For the image upload, we can actually just use basic HTML instead of Uppy. Sorry to ask this because I'm sure it took you a long time, but could we update this component so it doesn't use Uppy? I am also happy to do it myself and push to this branch. It would look something like this:
```
    <div>
      <input
        type="file"
        accept="image/*"
        ref={fileInputRef}
        onChange={handleChange}
      />
      <button onClick={handleClick}>Upload Image</button>
    </div>
```
(with Chakra components used as needed)

2024-03-17 06:32 UTC, maddiesolis commented on marketmate/src/app/api/images/products/route.ts
> +    } //else {
Remove commented out code

2024-03-17 06:32 UTC, maddiesolis commented on marketmate/src/app/api/images/products/route.ts
> +   // }
Same here

2024-03-17 18:10 UTC, JonCote commented on marketmate/src/app/_components/ImageUpload.tsx
Can I ask why no uppy? we can edit the styling of the uppy upload box to fit us better if that is the issue. The point of uppy is to provide a cleaner upload interface without having to program all of it our selves. uppy also just makes life a bit easier in general.

2024-03-17 20:39 UTC, maddiesolis commented on marketmate/src/app/_components/ImageUpload.tsx
Our design is just a button that triggers the default browse files modal. This is very easy to implement, it's just the code I sent above. No 3rd party library required.

2024-03-17 20:41 UTC, maddiesolis commented on marketmate/src/app/_components/ImageUpload.tsx
Actually you can just push what you have and we will change it when we implement the Edit Product and Edit Storefront modals.

2024-03-17 22:18 UTC, JonCote commented on marketmate/src/app/_components/ImageUpload.tsx
I can change it, that is fine. we just want a button no drag and drop or anything

2024-03-17 22:58 UTC, maddiesolis commented on marketmate/src/app/_components/ImageUpload.tsx
Yeah exactly, thanks so much :)

2024-03-18 01:13 UTC, JonCote commented
replaced uppy dashboard with basic html file uploader. still using uppy to abstract the uploading complexity and provide more reliable and secure uploads without needed to implement ourselves.

ImageUploadExample shows how the uploader works, 
- bucket is the bucket name to upload the image to
- returns the public url for the uploaded image 

![Screenshot 2024-03-17 180737](https://github.com/MarketMate-Seng480/MarketMate/assets/44143358/ecccd739-14be-4596-b6e0-20c2d8b10767)

2024-03-18 01:16 UTC, JonCote commented on marketmate/src/app/api/images/products/route.ts
> +    } //else {
file is not used and is now removed.

2024-03-18 01:16 UTC, JonCote commented on marketmate/src/app/api/images/products/route.ts
> +   // }
file is not used and is now removed.

2024-03-18 02:53 UTC, maddiesolis approved these changes

2024-03-18 02:53 UTC, merged